name: restaurant-api
on:
  push:
   branches: [master]
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: setup-dotnet
      uses: xt0rted/setup-dotnet@v1.5.0
      with:
          dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: build
      run: dotnet-build --no-restore
    - name: Test
      run: dotnet test
    
 
  

